### ISSUE TITLE
torchaudio doesn't get nightly aligned with pytorch and torchvsiion

### ISSUE THREAD

**Issue by jinfagang** [pytorch/audio#2610]
### 🐛 Describe the bug

```
pip3 install --pre torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
```

get:

Installing collected packages: torchaudio
Successfully installed torchaudio-0.14.0.dev20220603

today is 0807, is 0603 is nightly??????

error in sue:

```
 self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users//miniforge3/lib/python3.9/site-packages/torchaudio/lib/libtorchaudio.so, 0x0006): Symbol not found: __ZN2at14RecordFunctionC1ENS_11RecordScopeEb
```

### Versions

torch nightly

cc @ezyang @seemethere @malfet

**Comment by mthrok** [comment]
There is no official 0.14.0. The dev branch is 0.13. It might be some third party publishing the binary, or could be supply chain attack.

**Comment by mthrok** [comment]
There is no 0.14 listed in https://download.pytorch.org/whl/nightly/torchaudio/ nor https://download.pytorch.org/whl/nightly/torchaudio_nightly/ .

**Comment by mthrok** [comment]
Actualy there is, https://download.pytorch.org/whl/nightly/torchaudio/ ... what is happening ??

**Comment by mthrok** [comment]
@seemethere @malfet @atalman Can you delete 0.14.0 binaries from https://download.pytorch.org/whl/nightly/torchaudio/??

**Comment by atalman** [comment]
@malfet I think we only have following files:
[torchaudio-0.14.0.dev20220531-cp310-cp310-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220531-cp310-cp310-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220531-cp38-cp38-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220531-cp38-cp38-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220531-cp39-cp39-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220531-cp39-cp39-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220601-cp310-cp310-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220601-cp310-cp310-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220601-cp38-cp38-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220601-cp38-cp38-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220601-cp39-cp39-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220601-cp39-cp39-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220602-cp310-cp310-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220602-cp310-cp310-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220602-cp38-cp38-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220602-cp38-cp38-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220602-cp39-cp39-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220602-cp39-cp39-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220603-cp310-cp310-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220603-cp310-cp310-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220603-cp38-cp38-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220603-cp38-cp38-macosx_11_0_arm64.whl)
[torchaudio-0.14.0.dev20220603-cp39-cp39-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220603-cp39-cp39-macosx_11_0_arm64.whl)

I think its due to our work on 05.31-06.03 getting m1 builds ready

**Comment by malfet** [comment]
Deleted files and updated indicies...
@atalman can you please check other domain libraries as well? (Also, quite surprised how it happened to audio, as I did all the M1 build experiments against vision

**Comment by atalman** [comment]
Yes sounds good  will check now for vision and text

**Comment by atalman** [comment]
I think this issue was introduced by my initial commit, introducing m1 builds:
https://github.com/pytorch/audio/pull/2421

and later fixed by the following commit:
https://github.com/pytorch/audio/pull/2438

Sorry about this. Should have cleaned this up.

**Comment by malfet** [comment]
Closing, as looks like it's been fixed now. Please do not hesitate to reopen/open new issue if it happens again.

**Comment by mthrok** [comment]
@malfet The issue still presents.

It seems that `osx-arm64` torchaudio does not exist at all https://conda.anaconda.org/pytorch-nightly/osx-arm64

```
conda install pytorch torchaudio -c pytorch-nightly
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - torchaudio

Current channels:

  - https://conda.anaconda.org/pytorch-nightly/osx-arm64
  - https://conda.anaconda.org/pytorch-nightly/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by mthrok** [comment]
Looks like it's working now.

```
conda install pytorch torchaudio torchvision -c pytorch-nightly
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/moto/miniforge3

  added / updated specs:
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytorch-1.13.0.dev20220815 |          py3.9_0        43.1 MB  pytorch-nightly
    torchaudio-0.13.0.dev20220815|         py39_cpu         5.5 MB  pytorch-nightly
    torchvision-0.14.0.dev20220815|         py39_cpu         6.3 MB  pytorch-nightly
    ------------------------------------------------------------
                                           Total:        54.9 MB

The following NEW packages will be INSTALLED:

  torchaudio         pytorch-nightly/osx-arm64::torchaudio-0.13.0.dev20220815-py39_cpu
  torchvision        pytorch-nightly/osx-arm64::torchvision-0.14.0.dev20220815-py39_cpu

The following packages will be UPDATED:

  pytorch                        1.13.0.dev20220814-py3.9_0 --> 1.13.0.dev20220815-py3.9_0


Proceed ([y]/n)?
```
